name: SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Adjust as needed

      - name: Install dependencies
        run: npm ci

      - name: Run tests and generate coverage
        run: npm run test -- --coverage # adjust if your test script is different

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.9.1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=justinberg97_Sonar-Cloud-and-GitHub-Actions
            -Dsonar.organization=justinberg97
            -Dsonar.projectName=Sonar-Cloud-and-GitHub-Actions
            -Dsonar.sources=.
            -Dsonar.exclusions=node_modules/**,**/__tests__/**
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info